// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/netir_fr/PlasmicGlobalContextsProvider";

import { UnnamedGlobalGroupOfVariantsContextProvider } from "../components/plasmic/netir_fr/PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants";
import {
  PlasmicRemuneration,
  Head
} from "../components/plasmic/netir_fr/PlasmicRemuneration";
import type { PageProps } from "gatsby";
export { Head };

function Remuneration({ location, path, params }: PageProps) {
  // Use PlasmicRemuneration to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicRemuneration are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicRemuneration is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Gatsby "wrapRootElement" function
  // (https://www.gatsbyjs.com/docs/reference/config-files/gatsby-ssr#wrapRootElement).

  return (
    <UnnamedGlobalGroupOfVariantsContextProvider value={undefined}>
      <GlobalContextsProvider>
        <PageParamsProvider__
          route={path}
          params={params}
          query={Object.fromEntries(new URLSearchParams(location.search))}
        >
          <PlasmicRemuneration />
        </PageParamsProvider__>
      </GlobalContextsProvider>
    </UnnamedGlobalGroupOfVariantsContextProvider>
  );
}

export default Remuneration;
