/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oiQgZxfnSVj2maau7x1Bhf
// Component: a9-sw_kw8WM0

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic.module.css"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectcss
import * as sty from "./PlasmicMetiers.module.css"; // plasmic-import: a9-sw_kw8WM0/css

import WebdesignSvgIcon from "./icons/PlasmicIcon__WebdesignSvg"; // plasmic-import: dNdRY2MDtWlk/icon

createPlasmicElementProxy;

export type PlasmicMetiers__VariantMembers = {};
export type PlasmicMetiers__VariantsArgs = {};
type VariantPropType = keyof PlasmicMetiers__VariantsArgs;
export const PlasmicMetiers__VariantProps = new Array<VariantPropType>();

export type PlasmicMetiers__ArgsType = {
  nom?: string;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMetiers__ArgsType;
export const PlasmicMetiers__ArgProps = new Array<ArgPropType>(
  "nom",
  "children"
);

export type PlasmicMetiers__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  h5?: Flex__<"h5">;
};

export interface DefaultMetiersProps {
  nom?: string;
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function PlasmicMetiers__RenderFunc(props: {
  variants: PlasmicMetiers__VariantsArgs;
  args: PlasmicMetiers__ArgsType;
  overrides: PlasmicMetiers__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          nom: "Webdesign"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <WebdesignSvgIcon
              className={classNames(projectcss.all, sty.svg__jzVej)}
              role={"img"}
            />
          ),

          value: args.children
        })}
      </div>
      <h5
        data-plasmic-name={"h5"}
        data-plasmic-override={overrides.h5}
        className={classNames(
          projectcss.all,
          projectcss.h5,
          projectcss.__wab_text,
          sty.h5
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.nom;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Webdesign";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h5>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "h5"],
  freeBox: ["freeBox"],
  h5: ["h5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  h5: "h5";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMetiers__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMetiers__VariantsArgs;
    args?: PlasmicMetiers__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMetiers__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMetiers__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMetiers__ArgProps,
          internalVariantPropNames: PlasmicMetiers__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMetiers__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMetiers";
  } else {
    func.displayName = `PlasmicMetiers.${nodeName}`;
  }
  return func;
}

export const PlasmicMetiers = Object.assign(
  // Top-level PlasmicMetiers renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    h5: makeNodeComponent("h5"),

    // Metadata about props expected for PlasmicMetiers
    internalVariantProps: PlasmicMetiers__VariantProps,
    internalArgProps: PlasmicMetiers__ArgProps
  }
);

export default PlasmicMetiers;
/* prettier-ignore-end */
