/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oiQgZxfnSVj2maau7x1Bhf
// Component: grg6bA13A4jK

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic.module.css"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectcss
import * as sty from "./PlasmicSwitchMyOwnSwitch.module.css"; // plasmic-import: grg6bA13A4jK/css

createPlasmicElementProxy;

export type PlasmicSwitchMyOwnSwitch__VariantMembers = {
  isSwitchOn: "isSwitchOn";
};
export type PlasmicSwitchMyOwnSwitch__VariantsArgs = {
  isSwitchOn?: SingleBooleanChoiceArg<"isSwitchOn">;
};
type VariantPropType = keyof PlasmicSwitchMyOwnSwitch__VariantsArgs;
export const PlasmicSwitchMyOwnSwitch__VariantProps =
  new Array<VariantPropType>("isSwitchOn");

export type PlasmicSwitchMyOwnSwitch__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchMyOwnSwitch__ArgsType;
export const PlasmicSwitchMyOwnSwitch__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchMyOwnSwitch__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultSwitchMyOwnSwitchProps {
  isSwitchOn?: SingleBooleanChoiceArg<"isSwitchOn">;
  className?: string;
}

const $$ = {};

function PlasmicSwitchMyOwnSwitch__RenderFunc(props: {
  variants: PlasmicSwitchMyOwnSwitch__VariantsArgs;
  args: PlasmicSwitchMyOwnSwitch__ArgsType;
  overrides: PlasmicSwitchMyOwnSwitch__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isSwitchOn",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isSwitchOn
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootisSwitchOn]: hasVariant($state, "isSwitchOn", "isSwitchOn") }
      )}
      onClick={async event => {
        const $steps = {};

        $steps["updateIsSwitchOn"] = true
          ? (() => {
              const actionArgs = {
                vgroup: "isSwitchOn",
                operation: 2,
                value: "isSwitchOn"
              };
              return (({ vgroup, value }) => {
                if (typeof value === "string") {
                  value = [value];
                }

                const oldValue = $stateGet($state, vgroup);
                $stateSet($state, vgroup, !oldValue);
                return !oldValue;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateIsSwitchOn"] != null &&
          typeof $steps["updateIsSwitchOn"] === "object" &&
          typeof $steps["updateIsSwitchOn"].then === "function"
        ) {
          $steps["updateIsSwitchOn"] = await $steps["updateIsSwitchOn"];
        }
      }}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxisSwitchOn]: hasVariant(
            $state,
            "isSwitchOn",
            "isSwitchOn"
          )
        })}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchMyOwnSwitch__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchMyOwnSwitch__VariantsArgs;
    args?: PlasmicSwitchMyOwnSwitch__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchMyOwnSwitch__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchMyOwnSwitch__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchMyOwnSwitch__ArgProps,
          internalVariantPropNames: PlasmicSwitchMyOwnSwitch__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchMyOwnSwitch__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSwitchMyOwnSwitch";
  } else {
    func.displayName = `PlasmicSwitchMyOwnSwitch.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchMyOwnSwitch = Object.assign(
  // Top-level PlasmicSwitchMyOwnSwitch renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicSwitchMyOwnSwitch
    internalVariantProps: PlasmicSwitchMyOwnSwitch__VariantProps,
    internalArgProps: PlasmicSwitchMyOwnSwitch__ArgProps
  }
);

export default PlasmicSwitchMyOwnSwitch;
/* prettier-ignore-end */
