/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oiQgZxfnSVj2maau7x1Bhf
// Component: rkWe1EpKiaQz

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import DashboardDashboardLayout from "../../DashboardDashboardLayout"; // plasmic-import: KS-1W6sGklIw/component
import NavNavItem from "../../NavNavItem"; // plasmic-import: emjpN_Inho3r/component
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic.module.css"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectcss
import * as sty from "./PlasmicOldCompanyMissionsModifierMissions.module.css"; // plasmic-import: rkWe1EpKiaQz/css

import SettingsSvgrepoComSvgIcon from "./icons/PlasmicIcon__SettingsSvgrepoComSvg"; // plasmic-import: Zs9dSHGCwlTd/icon

createPlasmicElementProxy;

export type PlasmicOldCompanyMissionsModifierMissions__VariantMembers = {};
export type PlasmicOldCompanyMissionsModifierMissions__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicOldCompanyMissionsModifierMissions__VariantsArgs;
export const PlasmicOldCompanyMissionsModifierMissions__VariantProps =
  new Array<VariantPropType>();

export type PlasmicOldCompanyMissionsModifierMissions__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicOldCompanyMissionsModifierMissions__ArgsType;
export const PlasmicOldCompanyMissionsModifierMissions__ArgProps =
  new Array<ArgPropType>("children", "slot");

export type PlasmicOldCompanyMissionsModifierMissions__OverridesType = {
  root?: Flex__<"div">;
  dashboardLayout?: Flex__<typeof DashboardDashboardLayout>;
};

export interface DefaultOldCompanyMissionsModifierMissionsProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

const $$ = {};

export function Head() {
  return <></>;
}

function PlasmicOldCompanyMissionsModifierMissions__RenderFunc(props: {
  variants: PlasmicOldCompanyMissionsModifierMissions__VariantsArgs;
  args: PlasmicOldCompanyMissionsModifierMissions__ArgsType;
  overrides: PlasmicOldCompanyMissionsModifierMissions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dashboardLayout.isSidebarOpenn",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <DashboardDashboardLayout
            data-plasmic-name={"dashboardLayout"}
            data-plasmic-override={overrides.dashboardLayout}
            className={classNames("__wab_instance", sty.dashboardLayout)}
            isSidebarOpenn={generateStateValueProp($state, [
              "dashboardLayout",
              "isSidebarOpenn"
            ])}
            onIsSidebarOpennChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, [
                "dashboardLayout",
                "isSidebarOpenn"
              ]).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            slot={renderPlasmicSlot({
              defaultContents: (
                <div className={classNames(projectcss.all, sty.freeBox__lmtqy)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9HVq6
                    )}
                  >
                    {"Modifier la mission"}
                  </div>
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.form___3MssF),
                      formItems: [
                        { label: "Name", name: "name", inputType: "Text" },
                        {
                          label: "Message",
                          name: "message",
                          inputType: "Text Area"
                        }
                      ],
                      labelCol: { span: 8, horizontalOnly: true },
                      layout: "vertical",
                      mode: "advanced",
                      submitSlot: null,
                      wrapperCol: { span: 16, horizontalOnly: true }
                    };

                    return (
                      <FormWrapper {...child$Props}>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__j5Wk8
                          )}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zwEiT
                              )}
                            >
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 500 }}
                                >
                                  {"Nom de la mission"}
                                </span>
                              </React.Fragment>
                            </div>
                          }
                          name={"name"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__i7Wt0
                            )}
                          >
                            {
                              "Donnez un nom m\u00e9morisable \u00e0 cette mission"
                            }
                          </div>
                          {(() => {
                            const child$Props = {
                              className: classNames(
                                "__wab_instance",
                                sty.input__xZbIa
                              )
                            };

                            return <AntdInput {...child$Props} />;
                          })()}
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__pb6Fg
                          )}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sbl7Q
                              )}
                            >
                              {"D\u00e9tails des prestations"}
                            </div>
                          }
                          name={"message"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8JrBw
                            )}
                          >
                            {
                              "Pr\u00e9cisez en quoi consiste la mission, cette information sera pr\u00e9sente dans chaque facture"
                            }
                          </div>
                          {(() => {
                            const child$Props = {
                              className: classNames(
                                "__wab_instance",
                                sty.textArea__r7YuD
                              )
                            };

                            return <AntdTextArea {...child$Props} />;
                          })()}
                        </FormItemWrapper>
                        <AntdButton
                          className={classNames(
                            "__wab_instance",
                            sty.button__blskk
                          )}
                          submitsForm={true}
                          type={"primary"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vmcpg
                            )}
                          >
                            {"Modifier la mission"}
                          </div>
                        </AntdButton>
                      </FormWrapper>
                    );
                  })()}
                </div>
              ),
              value: args.slot
            })}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <NavNavItem
                    className={classNames(
                      "__wab_instance",
                      sty.navNavItem__tlQ8H
                    )}
                    slot={
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__uc0T3
                        )}
                        key={"menuItemKey1"}
                        onClick={async () => {
                          const $steps = {};

                          $steps["goToFreelanceMissions"] = true
                            ? (() => {
                                const actionArgs = {
                                  destination: `/freelance/missions`
                                };
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    __gatsbyNavigate(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToFreelanceMissions"] != null &&
                            typeof $steps["goToFreelanceMissions"] ===
                              "object" &&
                            typeof $steps["goToFreelanceMissions"].then ===
                              "function"
                          ) {
                            $steps["goToFreelanceMissions"] =
                              await $steps["goToFreelanceMissions"];
                          }
                        }}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8Zi4B
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 400 }}
                            >
                              {"Documents"}
                            </span>
                          </React.Fragment>
                        </div>
                      </AntdMenuItem>
                    }
                  >
                    <SettingsSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__d0TRw)}
                      role={"img"}
                    />
                  </NavNavItem>
                  <NavNavItem
                    className={classNames(
                      "__wab_instance",
                      sty.navNavItem___4GpaB
                    )}
                    slot={
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem___9Kxax
                        )}
                        key={"menuItemKey1"}
                        onClick={async () => {
                          const $steps = {};

                          $steps["goToFreelanceInvoices"] = true
                            ? (() => {
                                const actionArgs = {
                                  destination: `/freelance/invoices`
                                };
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    __gatsbyNavigate(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToFreelanceInvoices"] != null &&
                            typeof $steps["goToFreelanceInvoices"] ===
                              "object" &&
                            typeof $steps["goToFreelanceInvoices"].then ===
                              "function"
                          ) {
                            $steps["goToFreelanceInvoices"] =
                              await $steps["goToFreelanceInvoices"];
                          }
                        }}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__r8N4K
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 400 }}
                            >
                              {"Utilisateurs"}
                            </span>
                          </React.Fragment>
                        </div>
                      </AntdMenuItem>
                    }
                  >
                    <SettingsSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__bUgWt)}
                      role={"img"}
                    />
                  </NavNavItem>
                </React.Fragment>
              ),
              value: args.children
            })}
          </DashboardDashboardLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dashboardLayout"],
  dashboardLayout: ["dashboardLayout"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dashboardLayout: typeof DashboardDashboardLayout;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOldCompanyMissionsModifierMissions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOldCompanyMissionsModifierMissions__VariantsArgs;
    args?: PlasmicOldCompanyMissionsModifierMissions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<
      PlasmicOldCompanyMissionsModifierMissions__VariantsArgs,
      ReservedPropsType
    > &
    // Specify args directly as props
    Omit<
      PlasmicOldCompanyMissionsModifierMissions__ArgsType,
      ReservedPropsType
    > &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicOldCompanyMissionsModifierMissions__ArgProps,
          internalVariantPropNames:
            PlasmicOldCompanyMissionsModifierMissions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOldCompanyMissionsModifierMissions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOldCompanyMissionsModifierMissions";
  } else {
    func.displayName = `PlasmicOldCompanyMissionsModifierMissions.${nodeName}`;
  }
  return func;
}

export const PlasmicOldCompanyMissionsModifierMissions = Object.assign(
  // Top-level PlasmicOldCompanyMissionsModifierMissions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dashboardLayout: makeNodeComponent("dashboardLayout"),

    // Metadata about props expected for PlasmicOldCompanyMissionsModifierMissions
    internalVariantProps:
      PlasmicOldCompanyMissionsModifierMissions__VariantProps,
    internalArgProps: PlasmicOldCompanyMissionsModifierMissions__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOldCompanyMissionsModifierMissions;
/* prettier-ignore-end */
