/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oiQgZxfnSVj2maau7x1Bhf
// Component: EFKlzFDp6AyF

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic.module.css"; // plasmic-import: oiQgZxfnSVj2maau7x1Bhf/projectcss
import * as sty from "./PlasmicStepperComponentForm.module.css"; // plasmic-import: EFKlzFDp6AyF/css

import PadlockLockedSvgrepoComSvgIcon from "./icons/PlasmicIcon__PadlockLockedSvgrepoComSvg"; // plasmic-import: vpZ026OiGQE1/icon
import BarSvgrepoComSvgIcon from "./icons/PlasmicIcon__BarSvgrepoComSvg"; // plasmic-import: L_A-j4tKSVFr/icon
import Bag4SvgrepoComSvgIcon from "./icons/PlasmicIcon__Bag4SvgrepoComSvg"; // plasmic-import: xeojuuOAnBdF/icon
import DollarCircleSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__DollarCircleSvgrepoCom1Svg"; // plasmic-import: _B8xOJaCg617/icon
import UserSvgrepoCom4SvgIcon from "./icons/PlasmicIcon__UserSvgrepoCom4Svg"; // plasmic-import: QydiZu8DMym3/icon

createPlasmicElementProxy;

export type PlasmicStepperComponentForm__VariantMembers = {};
export type PlasmicStepperComponentForm__VariantsArgs = {};
type VariantPropType = keyof PlasmicStepperComponentForm__VariantsArgs;
export const PlasmicStepperComponentForm__VariantProps =
  new Array<VariantPropType>();

export type PlasmicStepperComponentForm__ArgsType = {
  children?: React.ReactNode;
  children2?: React.ReactNode;
  children3?: React.ReactNode;
  children4?: React.ReactNode;
};
type ArgPropType = keyof PlasmicStepperComponentForm__ArgsType;
export const PlasmicStepperComponentForm__ArgProps = new Array<ArgPropType>(
  "children",
  "children2",
  "children3",
  "children4"
);

export type PlasmicStepperComponentForm__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultStepperComponentFormProps {
  children?: React.ReactNode;
  children2?: React.ReactNode;
  children3?: React.ReactNode;
  children4?: React.ReactNode;
  className?: string;
}

const $$ = {};

function PlasmicStepperComponentForm__RenderFunc(props: {
  variants: PlasmicStepperComponentForm__VariantsArgs;
  args: PlasmicStepperComponentForm__ArgsType;
  overrides: PlasmicStepperComponentForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.columns__s9Bf)}>
            <div className={classNames(projectcss.all, sty.column__bAo6)}>
              <div className={classNames(projectcss.all, sty.freeBox__z6Zsu)}>
                <PadlockLockedSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__tMqiy)}
                  role={"img"}
                />
              </div>
              <BarSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__nALjF)}
                role={"img"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__ksjIb)}>
              <div className={classNames(projectcss.all, sty.freeBox__cg2E2)}>
                <div className={classNames(projectcss.all, sty.freeBox__w1EvE)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m8Uzf
                    )}
                  >
                    {"\u00c9tape 1"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s6XOt
                  )}
                >
                  {"Inscription"}
                </div>
              </div>
            </div>
          </div>
        ),
        value: args.children
      })}
      {renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.columns__oIlUb)}>
            <div className={classNames(projectcss.all, sty.column__yy9YL)}>
              <div className={classNames(projectcss.all, sty.freeBox__fYrgl)}>
                <Bag4SvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__vzgmN)}
                  role={"img"}
                />
              </div>
              <BarSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__l8ATs)}
                role={"img"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__rMpKc)}>
              <div className={classNames(projectcss.all, sty.freeBox__y0H5Z)}>
                <div className={classNames(projectcss.all, sty.freeBox__szUdl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8N7Hl
                    )}
                  >
                    {"\u00c9tape 2"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Y8SO
                  )}
                >
                  {"Votre entreprise"}
                </div>
              </div>
            </div>
          </div>
        ),
        value: args.children2
      })}
      {renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.columns__o4Leo)}>
            <div className={classNames(projectcss.all, sty.column__nfQpu)}>
              <div className={classNames(projectcss.all, sty.freeBox__wlI8Y)}>
                <DollarCircleSvgrepoCom1SvgIcon
                  className={classNames(projectcss.all, sty.svg__kA4If)}
                  role={"img"}
                />
              </div>
              <BarSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg___8C0)}
                role={"img"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__uV2Q)}>
              <div className={classNames(projectcss.all, sty.freeBox__tzO3O)}>
                <div className={classNames(projectcss.all, sty.freeBox__gLXpj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e5Zqp
                    )}
                  >
                    {"\u00c9tape 3"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xiLuN
                  )}
                >
                  {"Facturation"}
                </div>
              </div>
            </div>
          </div>
        ),
        value: args.children3
      })}
      {renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.columns__u2Q7V)}>
            <div className={classNames(projectcss.all, sty.column__xboS1)}>
              <div className={classNames(projectcss.all, sty.freeBox__usyXo)}>
                <UserSvgrepoCom4SvgIcon
                  className={classNames(projectcss.all, sty.svg__hkN1X)}
                  role={"img"}
                />
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column___5SA5V)}>
              <div className={classNames(projectcss.all, sty.freeBox__gvuCd)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5Bsz6)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xqdl6
                    )}
                  >
                    {"\u00c9tape 4"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oTg22
                  )}
                >
                  {"Responsable du compte"}
                </div>
              </div>
            </div>
          </div>
        ),
        value: args.children4
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStepperComponentForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStepperComponentForm__VariantsArgs;
    args?: PlasmicStepperComponentForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicStepperComponentForm__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicStepperComponentForm__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStepperComponentForm__ArgProps,
          internalVariantPropNames: PlasmicStepperComponentForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStepperComponentForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStepperComponentForm";
  } else {
    func.displayName = `PlasmicStepperComponentForm.${nodeName}`;
  }
  return func;
}

export const PlasmicStepperComponentForm = Object.assign(
  // Top-level PlasmicStepperComponentForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStepperComponentForm
    internalVariantProps: PlasmicStepperComponentForm__VariantProps,
    internalArgProps: PlasmicStepperComponentForm__ArgProps
  }
);

export default PlasmicStepperComponentForm;
/* prettier-ignore-end */
