/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oiQgZxfnSVj2maau7x1Bhf

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantslj7Q0YoPbE9U } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: LJ7Q0yoPbE9u/globalVariant
import {
  UnnamedGlobalGroupOfVariantsValue,
  useUnnamedGlobalGroupOfVariants
} from "./PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants"; // plasmic-import: Jf2u2zOFkH3G/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantslj7Q0YoPbE9U,
  unnamedGlobalGroupOfVariants: useUnnamedGlobalGroupOfVariants
});
