// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHomepageQuatuor,
  DefaultHomepageQuatuorProps
} from "./plasmic/netir_fr/PlasmicHomepageQuatuor";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HomepageQuatuorProps extends Omit<DefaultHomepageQuatuorProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHomepageQuatuorProps altogether and have
// total control over the props for your component.
export interface HomepageQuatuorProps extends DefaultHomepageQuatuorProps {}

function HomepageQuatuor_(
  props: HomepageQuatuorProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicHomepageQuatuor to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepageQuatuor are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all HomepageQuatuorProps here, but feel free
  // to do whatever works for you.

  return <PlasmicHomepageQuatuor frame313777={{ ref }} {...props} />;
}

const HomepageQuatuor = React.forwardRef(HomepageQuatuor_);
export default HomepageQuatuor;
